import type { Metadata } from "next";

import "./../globals.css";

export const metadata: Metadata = {
  title: "Cafe Paris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="relative z-10">{children}</div>;
}
